#!/usr/bin/env bash
# network-setup.sh — generate per-host vmbr0 + vmbr1 bridge config for Proxmox 8.x
#
# Usage:
#   bash network-setup.sh <vmbr0-ip> <lan-gateway> [nic] [--apply]
#
#   <vmbr0-ip>      MGMT bridge IP for this host on 10.0.0.0/24 (e.g. 10.0.0.1 for Host 1)
#   <lan-gateway>   Your LAN default gateway (e.g. 192.168.1.1 or 10.0.0.254)
#   [nic]           Physical NIC name (default: eno1 — common on Dell/HP servers)
#   [--apply]       Write config to /etc/network/interfaces (default: DRY-RUN, preview only)
#
# Examples (dry-run):
#   bash network-setup.sh 10.0.0.1 192.168.1.1
#   bash network-setup.sh 10.0.0.2 192.168.1.1 enp2s0
#
# Examples (apply — destructive!):
#   bash network-setup.sh 10.0.0.1 192.168.1.1 eno1 --apply
#   bash network-setup.sh 10.0.0.6 192.168.1.1 eno1 --apply   # Host 6 (caldera-vm + kali)
#
# IP address plan (D-NEW-08, D-NEW-09 — do NOT use these as vmbr0 host IPs):
#   elastic-vm MGMT:  10.0.0.10  (Host 1 — VM address, NOT the host bridge)
#   caldera-vm MGMT:  10.0.0.20  (Host 6 — VM address, NOT the host bridge)
#   The host's vmbr0 address is operator-assigned per host (this script's $1 parameter).
#   Recommended: Host 1 → 10.0.0.1, Host 2 → 10.0.0.2, ..., Host 6 → 10.0.0.6
#
# !! CRITICAL SAFETY RULE — vmbr1 bridge-ports !!
#   vmbr1 MUST use:  bridge-ports eno1.10  (VLAN 10 sub-interface — switch-isolated, OK)
#   OR use:          bridge-ports none      (standalone host with no cross-host TARGET routing)
#   NEVER use:       bridge-ports eno1      (bare physical NIC — bridges TARGET traffic directly
#                                            onto the untagged LAN, breaking D-02 air-gap)
#   This is enforced by this script — vmbr1 always gets bridge-ports eno1.10.
#
# What this script creates:
#   - vmbr0: MGMT bridge, static IP on 10.0.0.0/24, physical NIC uplink (eno1), routes to LAN
#   - vmbr1: TARGET bridge, static IP 10.10.10.1/24, VLAN sub-interface eno1.10 (VLAN 10 tagged),
#            NO direct physical NIC uplink — isolated from LAN at hypervisor level (D-02)
#   - iface eno1.10 inet manual: VLAN 10 sub-interface declaration (required before vmbr1 stanza)
#
# After applying:
#   ifreload -a            (Proxmox-native — reloads changed interfaces without full restart)
#   OR: systemctl restart networking  (fallback — less preferred, causes brief connectivity loss)
#   THEN: bash verify-isolation.sh    (confirm vmbr1 has no bare NIC uplink)
#
# Reference:
#   https://pve.proxmox.com/wiki/Network_Configuration [VERIFIED]
#   Option A: Traditional VLAN sub-interface (single VLAN, simpler than VLAN-aware bridge)

set -euo pipefail

# ── argument parsing ──────────────────────────────────────────────────────────
if [[ $# -lt 2 ]]; then
    echo "Usage: $0 <vmbr0-ip> <lan-gateway> [nic] [--apply]" >&2
    echo "  Example: $0 10.0.0.1 192.168.1.1" >&2
    echo "  Example: $0 10.0.0.1 192.168.1.1 eno1 --apply" >&2
    exit 1
fi

VMBR0_IP="$1"
LAN_GW="$2"
NIC="${3:-eno1}"
APPLY=false

# Allow --apply anywhere in args
for arg in "$@"; do
    if [[ "$arg" == "--apply" ]]; then
        APPLY=true
    fi
done

# If third arg is --apply (user skipped nic param), reset NIC to default
if [[ "$NIC" == "--apply" ]]; then
    NIC="eno1"
fi

VLAN_IFACE="${NIC}.10"    # VLAN 10 sub-interface
VMBR0_NETMASK="24"        # 10.0.0.0/24
VMBR1_IP="10.10.10.1"     # Proxmox host vmbr1 address (same on every host — each host is a /24 router)
VMBR1_NETMASK="24"        # 10.10.10.0/24

# ── validate IP format (basic) ────────────────────────────────────────────────
validate_ip() {
    local ip="$1"
    if ! echo "$ip" | grep -Eq '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'; then
        echo "ERROR: '$ip' does not look like a valid IPv4 address" >&2
        exit 1
    fi
}
validate_ip "$VMBR0_IP"
validate_ip "$LAN_GW"

# ── generate config ───────────────────────────────────────────────────────────
CONFIG=$(cat <<INTERFACES_EOF
# /etc/network/interfaces — generated by network-setup.sh
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Host vmbr0 IP: ${VMBR0_IP}/24   NIC: ${NIC}
# Host vmbr1 IP: ${VMBR1_IP}/24   VLAN sub-iface: ${VLAN_IFACE}
#
# ARCHITECTURE:
#   vmbr0 = MGMT network (10.0.0.0/24) — connects to LAN via physical NIC
#   vmbr1 = TARGET network (10.10.10.0/24) — cross-host via VLAN 10 on managed switch
#
# ISOLATION GUARANTEE (D-02):
#   vmbr1 uses bridge-ports ${VLAN_IFACE} (VLAN 10 sub-interface), NOT bridge-ports ${NIC}.
#   The managed switch must have NO inter-VLAN routing between VLAN 10 and the LAN VLAN.
#   See SWITCH-VLAN10.md for switch configuration steps.

source /etc/network/interfaces.d/*

# Loopback
auto lo
iface lo inet loopback

# Physical NIC — managed by the two bridges below (no standalone IP)
iface ${NIC} inet manual

# VLAN 10 sub-interface — REQUIRED before vmbr1 stanza
# This declares the 802.1Q tagged sub-interface; the bridge handles untagging for VMs.
iface ${VLAN_IFACE} inet manual

# vmbr0 — MGMT bridge (10.0.0.0/24, connects to LAN)
# Elastic Agents, SSH, and management traffic use this bridge.
auto vmbr0
iface vmbr0 inet static
        address ${VMBR0_IP}/${VMBR0_NETMASK}
        gateway ${LAN_GW}
        bridge-ports ${NIC}
        bridge-stp off
        bridge-fd 0

# vmbr1 — TARGET bridge (10.10.10.0/24, air-gapped from LAN)
# All victim VMs (dc01, exchange01, sql01, ws01, ws02, kali) attach to this bridge.
# bridge-ports ${VLAN_IFACE}: VLAN 10 tagged traffic from the managed switch trunk port
#   feeds into this bridge — VMs on vmbr1 see VLAN 10 traffic untagged.
# NEVER set bridge-ports to a bare physical NIC (e.g. bridge-ports ${NIC}) on vmbr1 —
#   that would bridge TARGET traffic directly onto the untagged LAN (D-02 violation).
auto vmbr1
iface vmbr1 inet static
        address ${VMBR1_IP}/${VMBR1_NETMASK}
        bridge-ports ${VLAN_IFACE}
        bridge-stp off
        bridge-fd 0
INTERFACES_EOF
)

# ── output / apply ────────────────────────────────────────────────────────────
echo "=== network-setup.sh ==="
echo "    vmbr0: ${VMBR0_IP}/${VMBR0_NETMASK}  gateway=${LAN_GW}  NIC=${NIC}"
echo "    vmbr1: ${VMBR1_IP}/${VMBR1_NETMASK}  bridge-ports=${VLAN_IFACE}  (VLAN 10 sub-iface)"
echo ""

if [[ "$APPLY" == "false" ]]; then
    echo ">>> DRY-RUN — config NOT written (pass --apply to write to /etc/network/interfaces)"
    echo ""
    echo "--- Generated /etc/network/interfaces ---"
    echo "$CONFIG"
    echo "-----------------------------------------"
    echo ""
    echo "Review the config above, then re-run with --apply:"
    echo "  bash $0 ${VMBR0_IP} ${LAN_GW} ${NIC} --apply"
    echo ""
    echo "After applying, run:"
    echo "  ifreload -a                         # reload bridges without full restart"
    echo "  bash verify-isolation.sh            # confirm vmbr1 has no bare NIC uplink"
else
    # Safety check: refuse to overwrite if vmbr1 already has a bare physical NIC
    if [[ -f /etc/network/interfaces ]]; then
        EXISTING_VMBR1=$(grep -A5 'auto vmbr1' /etc/network/interfaces | grep 'bridge-ports' | grep -v '^#' || true)
        if echo "$EXISTING_VMBR1" | grep -q "bridge-ports ${NIC}$"; then
            echo "WARNING: existing /etc/network/interfaces has bridge-ports ${NIC} on vmbr1"
            echo "         This is a bare physical NIC — replacing with the correct eno1.10 config."
        fi
    fi

    # Backup existing config
    if [[ -f /etc/network/interfaces ]]; then
        BACKUP="/etc/network/interfaces.bak.$(date +%Y%m%d%H%M%S)"
        cp /etc/network/interfaces "$BACKUP"
        echo "Backup created: $BACKUP"
    fi

    echo "$CONFIG" > /etc/network/interfaces
    echo ""
    echo "=== APPLIED: /etc/network/interfaces written ==="
    echo ""
    echo "Next steps:"
    echo "  1. ifreload -a                       # apply changes (or: systemctl restart networking)"
    echo "  2. bash verify-isolation.sh          # confirm vmbr1 bridge-ports is clean"
    echo "  3. brctl show vmbr0 vmbr1            # visual confirmation"
fi
